name: CD – Deploy (GitHub Environment)

on:
  push:
    branches: [main]          # cámbialo a develop si quieres
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**
            !**/*.map

      # Crea un "deployment" al environment production sin requerir checks externos
      - name: Create deployment
        id: create_deploy
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const res = await github.rest.repos.createDeployment({
              owner, repo,
              ref: context.sha,
              environment: 'production',
              description: 'Build listo. Artefacto adjunto en este run.',
              auto_merge: false,
              required_contexts: [],       // clave: no requiere checks previos
              transient_environment: false,
              production_environment: true
            });
            return res.data.id;

      - name: Mark deployment as successful
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const deployment_id = '${{ steps.create_deploy.outputs.result }}';
            await github.rest.repos.createDeploymentStatus({
              owner, repo, deployment_id,
              state: 'success',
              environment_url: `https://github.com/${owner}/${repo}/actions/runs/${process.env.GITHUB_RUN_ID}`,
              log_url: `https://github.com/${owner}/${repo}/actions/runs/${process.env.GITHUB_RUN_ID}`,
              description: 'Despliegue registrado en GitHub (ver artefacto dist).'
            });
