name: CI – Build, Lint, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Type check (optional)
        run: npm run typecheck --if-present

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build project
        run: npm run build --if-present

      - name: Smoke test (optional)
        run: npm run smoke --if-present
